// Lucky's photos and videos, supplied by the site owner. Dates indicate collection dates.
export const site = { title: 'Lucky 的日常', description: '有 Lucky 的普通日子。' };
export const notes = [
  {
    id: 'lucky-at-the-night-window', date: '2026-10-09', title: '夜里的窗边',
    description: '窗外亮着灯，Lucky 回头看了一眼。',
    paragraphs: ['夜色里，Lucky 待在窗边，回头望向镜头。'],
    photo: 'assets/lucky-photo-07.jpg', width: 720, height: 1280,
    alt: 'Lucky 夜里趴在窗边，身后有窗框和窗外灯光', caption: '夜色里的 Lucky',
  },
  {
    id: 'lucky-touching-a-finger-at-keyboard', date: '2026-10-09', title: '键盘边的小碰爪',
    description: '屏幕下伸出一只小爪，碰到手指。',
    paragraphs: ['电脑屏幕下，Lucky 伸出前爪，轻轻碰到键盘旁的手指。'],
    photo: 'assets/lucky-photo-08.jpg', width: 719, height: 1280,
    alt: '电脑屏幕下，Lucky 的前爪碰着人的手指，旁边是键盘', caption: '小爪碰到手指',
  },
  {
    id: 'lucky-reaching-toward-the-desk', date: '2026-10-09', title: '伸长身子看一看',
    description: '后脚踩着坐垫，前爪搭到木柜边。',
    paragraphs: ['Lucky 站在绿色坐垫上，伸长身子，朝旁边的木柜看去。'],
    photo: 'assets/lucky-photo-09.jpg', width: 720, height: 1280,
    alt: 'Lucky 后脚站在绿色坐垫上，前脚搭着旁边的木柜', caption: '伸长身子的 Lucky',
  },
  {
    id: 'lucky-by-the-floral-cushion', date: '2026-10-09', title: '花纹靠垫前的小团子',
    description: '收起小爪，在绿色坐垫上安静待着。',
    paragraphs: ['Lucky 蜷伏在绿色坐垫上，身后是印着深色花朵的靠垫。'],
    photo: 'assets/lucky-photo-10.jpg', width: 720, height: 1280,
    alt: 'Lucky 蜷伏在绿色坐垫上，身后是印着深色花朵的靠垫', caption: '沙发上的小团子',
  },
  {
    id: 'lucky-fluffy-back', date: '2026-10-09', title: '蓬蓬的背影',
    description: '背对镜头坐着，毛毛蓬成一团。',
    paragraphs: ['Lucky 背对镜头，坐在蓝边白色垫子上，留下一张蓬松的背影。'],
    photo: 'assets/lucky-photo-11.jpg', width: 720, height: 1280,
    alt: 'Lucky 背对镜头坐在蓝边白色垫子上，一只手在它身旁', caption: 'Lucky 的背影',
  },
  {
    id: 'lucky-peeking-over-the-table', date: '2026-10-09', title: '桌边探出小脑袋',
    description: '从桌边探出头，露出一点小舌尖。',
    paragraphs: ['有人轻扶着桌边的 Lucky，它低头探向桌沿，小舌尖也一起出镜了。'],
    photo: 'assets/lucky-photo-12.jpg', width: 1280, height: 720, previewFit: 'contain',
    alt: '有人扶着桌边的 Lucky，Lucky 探出桌沿，露出一点舌尖', caption: '探头的小瞬间',
  },
  {
    id: 'lucky-curled-up', date: '2026-10-09', title: '缩成一团的毛球',
    description: '蜷在坐垫一角，蓬松得像一团云。',
    paragraphs: ['Lucky 在花纹坐垫上蜷成一团，蓬松的背和灰色的尾巴露在外面。'],
    photo: 'assets/lucky-photo-13.jpg', width: 720, height: 1280,
    alt: 'Lucky 在花纹坐垫上蜷成一团，露出蓬松的背和灰色尾巴', caption: '一团毛茸茸的 Lucky',
  },
  {
    id: 'lucky-holding-a-finger', date: '2026-10-09', title: '小爪抱住手指',
    description: '仰躺在腿上，轻轻抱住伸来的手指。',
    paragraphs: ['Lucky 仰躺在腿上，用前爪抱住伸来的手指，圆圆的眼睛望向身边的人。'],
    photo: 'assets/lucky-photo-05.jpg', width: 1280, height: 720, previewFit: 'contain',
    alt: 'Lucky 仰躺在腿上，前爪抱着一根手指', caption: '被小爪轻轻抱住',
  },
  {
    id: 'lucky-and-the-blue-feather', date: '2026-10-09', title: '沙发上的蓝色羽毛',
    description: '抬起头，望向蓝色的羽毛逗猫棒。',
    paragraphs: ['Lucky 站在沙发旁，抬起小脑袋望着蓝色的羽毛逗猫棒。'],
    photo: 'assets/lucky-photo-06.jpg', width: 719, height: 1280,
    alt: 'Lucky 在沙发边抬头望向蓝色的羽毛逗猫棒', caption: 'Lucky 和蓝色羽毛',
  },
  {
    id: 'lucky-in-the-yellow-bed', date: '2026-10-09', title: '窗边的黄色小窝',
    description: '在窗边的小窝里，抬头看看周围。',
    paragraphs: ['Lucky 待在窗边笼子里的黄色小窝上，抬起头张望。'],
    photo: 'assets/lucky-07.jpg', video: 'assets/lucky-07.mp4', duration: '00:10',
    width: 360, height: 480,
    alt: 'Lucky 在窗边笼子里的黄色小窝上抬头张望', caption: '窗边的 Lucky',
  },
  {
    id: 'lucky-in-the-litter-box', date: '2026-10-09', title: '猫砂盆里的小眼神',
    description: '在粉白色的猫砂盆里，抬头看看镜头。',
    paragraphs: ['Lucky 待在笼子里的粉白色猫砂盆中，抬头看向镜头。'],
    photo: 'assets/lucky-08.jpg', video: 'assets/lucky-08.mp4', duration: '00:06',
    width: 544, height: 960,
    alt: 'Lucky 待在笼子里的粉白色猫砂盆中，抬头望向镜头', caption: '猫砂盆里的 Lucky',
  },
  {
    id: 'lucky-window-corner', date: '2026-10-09', title: '窗边的一角',
    description: 'Lucky 生活里的窗边客厅。',
    paragraphs: ['镜头记录了窗边的客厅：沙发、绿植和窗外的景色。这里是 Lucky 生活的一角。'],
    photo: 'assets/lucky-06.jpg', video: 'assets/lucky-06.mp4', duration: '00:06',
    width: 360, height: 480,
    alt: '窗边客厅里有沙发、绿植与窗外景色', caption: 'Lucky 生活的小角落',
  },
  {
    id: 'lucky-looking-up-at-the-carrier-door', date: '2026-10-09', title: '箱顶传来的动静',
    description: '有人把手放在航空箱顶，Lucky 抬头望了望。',
    paragraphs: ['有人把手放在航空箱顶，Lucky 待在箱内，抬起头看向上方。'],
    photo: 'assets/lucky-09.jpg', video: 'assets/lucky-09.mp4', duration: '00:07',
    width: 720, height: 1280,
    alt: '有人把手放在航空箱顶，Lucky 在箱内抬头', caption: '航空箱里的小抬头',
  },
  {
    id: 'lucky-turning-in-the-carrier', date: '2026-10-09', title: '在航空箱里转个身',
    description: '低下头，再慢慢转过身。',
    paragraphs: ['Lucky 在航空箱里低下头，慢慢转过身；箱外透出一片绿色。'],
    photo: 'assets/lucky-10.jpg', video: 'assets/lucky-10.mp4', duration: '00:11',
    width: 544, height: 960,
    alt: 'Lucky 在航空箱里低头转身，箱外有一片绿色', caption: '箱里的另一瞬间',
  },
  {
    id: 'lucky-by-the-sofa-cover', date: '2026-10-09', title: '沙发边慢慢走',
    description: '走到沙发布罩旁，凑近看一看。',
    paragraphs: ['Lucky 沿着沙发边走动，慢慢靠近垂下来的布罩。'],
    photo: 'assets/lucky-11.jpg', video: 'assets/lucky-11.mp4', duration: '00:10',
    width: 720, height: 1280,
    alt: 'Lucky 在沙发布罩旁走动并靠近布罩', caption: '沙发边的 Lucky',
  },
  {
    id: 'lucky-watching-the-bird', date: '2026-10-09', title: '抬头看小鸟',
    description: 'Lucky 抬起头，小鸟停在笼顶。',
    paragraphs: ['Lucky 在白色笼子里抬头，笼顶停着一只黄绿色的小鸟。'],
    photo: 'assets/lucky-04.jpg', video: 'assets/lucky-04.mp4', duration: '00:06',
    width: 544, height: 960, previewFit: 'contain',
    alt: 'Lucky 在白色笼子里抬头，黄绿色小鸟停在笼顶', caption: '笼顶的小鸟',
  },
  {
    id: 'lucky-and-a-small-neighbor', date: '2026-10-09', title: '椅脚旁的小相遇',
    description: '椅脚旁的 Lucky，地板上的小鸟。',
    paragraphs: ['Lucky 在椅脚旁望向地板上的黄绿色小鸟。'],
    photo: 'assets/lucky-05.jpg', video: 'assets/lucky-05.mp4', duration: '00:11',
    width: 1280, height: 720, previewFit: 'contain',
    alt: 'Lucky 待在椅脚旁，旁边的地板上站着一只黄绿色小鸟', caption: 'Lucky 和小鸟的同框',
  },
  {
    id: 'lucky-at-the-bowl', date: '2026-10-09', title: '碗边的小脑袋',
    description: '毛茸茸的小脸，凑在粉色小碗旁。',
    paragraphs: ['Lucky 低着头，小脑袋凑在粉色的食盆旁。'],
    photo: 'assets/lucky-photo-01.jpg', width: 719, height: 1280,
    alt: 'Lucky 在笼子里低着头，小脸凑在粉色食盆旁', caption: '碗边的 Lucky',
  },
  {
    id: 'lucky-sleeping-on-the-back', date: '2026-10-09', title: '睡觉，四脚朝天',
    description: '仰面躺着，小爪爪也放松了。',
    paragraphs: ['Lucky 仰面躺在印花布上，闭着眼睛，露出粉色的小爪垫。'],
    photo: 'assets/lucky-photo-02.jpg', width: 719, height: 1280,
    alt: 'Lucky 闭着眼睛仰面躺在印花布上，四只小爪自然伸开', caption: '四脚朝天的小睡姿',
  },
  {
    id: 'lucky-little-paws', date: '2026-10-09', title: '举起小爪爪',
    description: '一只小爪靠着脸，另一只举起来。',
    paragraphs: ['Lucky 仰面躺着，一只前爪靠在脸旁，另一只前爪露出粉色的小爪垫。'],
    photo: 'assets/lucky-photo-03.jpg', width: 719, height: 1280,
    alt: 'Lucky 仰面躺着，两只前爪举到脸旁，露出粉色的爪垫', caption: 'Lucky 的小爪爪',
  },
  {
    id: 'lucky-hiding-the-face', date: '2026-10-09', title: '把脸藏进小爪爪',
    description: '前爪遮住小脸，安安静静地躺着。',
    paragraphs: ['Lucky 躺在印花布上，用毛茸茸的前爪遮住小脸。'],
    photo: 'assets/lucky-photo-04.jpg', width: 719, height: 1280,
    alt: 'Lucky 仰面躺在印花布上，用前爪遮住脸', caption: '小爪爪后面，是 Lucky',
  },
  {
    id: 'lucky-in-the-carrier', date: '2026-10-09', title: '航空箱里的小眼神',
    description: '转头看看，再看看镜头。',
    paragraphs: ['Lucky 待在航空箱里，转头张望，又看向镜头。'],
    photo: 'assets/lucky-01.jpg', video: 'assets/lucky-01.mp4', duration: '00:06',
    width: 544, height: 960,
    alt: 'Lucky 在航空箱里望向镜头，前爪放在箱内', caption: 'Lucky 的小眼神',
  },
  {
    id: 'lucky-looking-up', date: '2026-10-09', title: '抬头看镜头',
    description: '一小段 Lucky 的近距离记录。',
    paragraphs: ['Lucky 在航空箱内的垫子上，抬头看向镜头。'],
    photo: 'assets/lucky-02.jpg', video: 'assets/lucky-02.mp4', duration: '00:03',
    width: 720, height: 1280,
    alt: 'Lucky 在航空箱里抬头看着镜头', caption: '抬头的这一瞬间',
  },
  {
    id: 'lucky-exploring', date: '2026-10-09', title: '出来走走啦',
    description: '箱门打开了，Lucky 出来走走。',
    paragraphs: ['Lucky 在瓷砖地面上走动，停在打开的航空箱门旁。'],
    photo: 'assets/lucky-03.jpg', video: 'assets/lucky-03.mp4', duration: '00:11',
    width: 720, height: 1280,
    alt: 'Lucky 在瓷砖地面上走动，旁边是打开的航空箱门', caption: '出来走走的 Lucky',
  },
];
